// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgDc1Yl1SedOCRq5RSOf5K5igfBFafzTU',
    appId: '1:869641834843:web:96467e4fb224153f9d4a7e',
    messagingSenderId: '869641834843',
    projectId: 'app-acai-aeebe',
    authDomain: 'app-acai-aeebe.firebaseapp.com',
    storageBucket: 'app-acai-aeebe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCulEWKlAc1NPS9OPDfIxjTNZfZMQfA9kg',
    appId: '1:869641834843:android:bfa8cb7fe3a0b3cd9d4a7e',
    messagingSenderId: '869641834843',
    projectId: 'app-acai-aeebe',
    storageBucket: 'app-acai-aeebe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-uQyyJpRWOA0E8HtrXuT-OluqlCwC26w',
    appId: '1:869641834843:ios:362af783c9b105399d4a7e',
    messagingSenderId: '869641834843',
    projectId: 'app-acai-aeebe',
    storageBucket: 'app-acai-aeebe.appspot.com',
    iosClientId: '869641834843-ugejo57a686vd8gp1i7e93mqfhp1slk1.apps.googleusercontent.com',
    iosBundleId: 'com.acaiboca.appAcai',
  );
}
